const data = {
  code: 200,
  msg: '成功',
  data: [
    {
      id: 1,
      name: 'A-人类生活必需',
      aliaName: 'A-人类生活必需',
      code: 'A',
      icon: null,
      cover: null,
      sort: 1,
      description: null,
      parentIds: null,
      parentId: 0,
      children: [
        {
          id: 9,
          name: 'A01农业；林业；畜牧业；狩猎；诱捕；捕鱼',
          aliaName: 'A01农业；林业；畜牧业；狩猎；诱捕；捕鱼',
          code: 'A01',
          icon: null,
          cover: null,
          sort: 1,
          description: null,
          parentIds: '1',
          parentId: 1,
          children: [],
        },
        {
          id: 10,
          name: 'A21焙烤；制作或处理面团的设备；焙烤用面团〔1，8〕',
          aliaName: 'A21焙烤；制作或处理面团的设备；焙烤用面团〔1，8〕',
          code: 'A21',
          icon: null,
          cover: null,
          sort: 2,
          description: null,
          parentIds: '1',
          parentId: 1,
          children: [],
        },
        {
          id: 11,
          name: 'A22屠宰； 肉品处理； 家禽或鱼的加工',
          aliaName: 'A22屠宰； 肉品处理； 家禽或鱼的加工',
          code: 'A22',
          icon: null,
          cover: null,
          sort: 3,
          description: null,
          parentIds: '1',
          parentId: 1,
          children: [],
        },
        {
          id: 12,
          name: 'A23其他类不包含的食品或食料；及其处理',
          aliaName: 'A23其他类不包含的食品或食料；及其处理',
          code: 'A23',
          icon: null,
          cover: null,
          sort: 4,
          description: null,
          parentIds: '1',
          parentId: 1,
          children: [],
        },
        {
          id: 13,
          name: 'A41服装',
          aliaName: 'A41服装',
          code: 'A41',
          icon: null,
          cover: null,
          sort: 5,
          description: null,
          parentIds: '1',
          parentId: 1,
          children: [],
        },
        {
          id: 138,
          name: 'A24烟草；雪茄烟；纸烟；吸烟者用品',
          aliaName: 'A24烟草；雪茄烟；纸烟；吸烟者用品',
          code: 'A24',
          icon: null,
          cover: null,
          sort: 5,
          description: null,
          parentIds: '1',
          parentId: 1,
          children: [],
        },
        {
          id: 14,
          name: 'A42帽类制品',
          aliaName: 'A42帽类制品',
          code: 'A42',
          icon: null,
          cover: null,
          sort: 6,
          description: null,
          parentIds: '1',
          parentId: 1,
          children: [],
        },
        {
          id: 15,
          name: 'A43鞋类',
          aliaName: 'A43鞋类',
          code: 'A43',
          icon: null,
          cover: null,
          sort: 7,
          description: null,
          parentIds: '1',
          parentId: 1,
          children: [],
        },
        {
          id: 16,
          name: 'A44服饰缝纫用品；珠宝',
          aliaName: 'A44服饰缝纫用品；珠宝',
          code: 'A44',
          icon: null,
          cover: null,
          sort: 8,
          description: null,
          parentIds: '1',
          parentId: 1,
          children: [],
        },
        {
          id: 17,
          name: 'A45手携物品或旅行品',
          aliaName: 'A45手携物品或旅行品',
          code: 'A45',
          icon: null,
          cover: null,
          sort: 9,
          description: null,
          parentIds: '1',
          parentId: 1,
          children: [],
        },
        {
          id: 18,
          name: 'A46刷类制品',
          aliaName: 'A46刷类制品',
          code: 'A46',
          icon: null,
          cover: null,
          sort: 10,
          description: null,
          parentIds: '1',
          parentId: 1,
          children: [],
        },
        {
          id: 19,
          name: 'A47家具；家庭用的物品或设备；咖啡磨；香料磨；一般吸尘器',
          aliaName: 'A47家具；家庭用的物品或设备；咖啡磨；香料磨；一般吸尘器',
          code: 'A47',
          icon: null,
          cover: null,
          sort: 11,
          description: null,
          parentIds: '1',
          parentId: 1,
          children: [],
        },
        {
          id: 20,
          name: 'A61医学或兽医学；卫生学',
          aliaName: 'A61医学或兽医学；卫生学',
          code: 'A61',
          icon: null,
          cover: null,
          sort: 12,
          description: null,
          parentIds: '1',
          parentId: 1,
          children: [],
        },
        {
          id: 21,
          name: 'A62救生；消防',
          aliaName: 'A62救生；消防',
          code: 'A62',
          icon: null,
          cover: null,
          sort: 13,
          description: null,
          parentIds: '1',
          parentId: 1,
          children: [],
        },
        {
          id: 22,
          name: 'A63运动；游戏；娱乐活动',
          aliaName: 'A63运动；游戏；娱乐活动',
          code: 'A63',
          icon: null,
          cover: null,
          sort: 14,
          description: null,
          parentIds: '1',
          parentId: 1,
          children: [],
        },
        {
          id: 23,
          name: 'A99本部其他类目中不包括的技术主题〔８〕',
          aliaName: 'A99本部其他类目中不包括的技术主题〔８〕',
          code: 'A99',
          icon: null,
          cover: null,
          sort: 15,
          description: null,
          parentIds: '1',
          parentId: 1,
          children: [],
        },
      ],
    },
    {
      id: 2,
      name: 'B-作业；运输',
      aliaName: 'B-作业；运输',
      code: 'B',
      icon: null,
      cover: null,
      sort: 2,
      description: null,
      parentIds: null,
      parentId: 0,
      children: [
        {
          id: 24,
          name: 'B01一般的物理或化学的方法或装置',
          aliaName: 'B01一般的物理或化学的方法或装置',
          code: 'B01',
          icon: null,
          cover: null,
          sort: 1,
          description: null,
          parentIds: '2',
          parentId: 2,
          children: [],
        },
        {
          id: 25,
          name: 'B02破碎、磨粉或粉碎；谷物碾磨的预处理',
          aliaName: 'B02破碎、磨粉或粉碎；谷物碾磨的预处理',
          code: 'B02',
          icon: null,
          cover: null,
          sort: 2,
          description: null,
          parentIds: '2',
          parentId: 2,
          children: [],
        },
        {
          id: 26,
          name: 'B03 用液体或用风力摇床或风力跳汰机分离固体物料；从固体物料或流体中分离固体物料的磁或静电分离；高压电场分离〔5〕',
          aliaName: 'B03 用液体或用风力摇床或风力跳汰机分离固体物料；从固体物料或流体中分离固体物料的磁或静电分离；高压电场分离〔5〕',
          code: 'B03',
          icon: null,
          cover: null,
          sort: 3,
          description: null,
          parentIds: '2',
          parentId: 2,
          children: [],
        },
        {
          id: 27,
          name: 'B04用于实现物理或化学工艺过程的离心装置或离心机',
          aliaName: 'B04用于实现物理或化学工艺过程的离心装置或离心机',
          code: 'B04',
          icon: null,
          cover: null,
          sort: 4,
          description: null,
          parentIds: '2',
          parentId: 2,
          children: [],
        },
        {
          id: 28,
          name: 'B05一般喷射或雾化；对表面涂覆液体或其他流体的一般方法〔2〕',
          aliaName: 'B05一般喷射或雾化；对表面涂覆液体或其他流体的一般方法〔2〕',
          code: 'B05',
          icon: null,
          cover: null,
          sort: 5,
          description: null,
          parentIds: '2',
          parentId: 2,
          children: [],
        },
        {
          id: 29,
          name: 'B06一般机械振动的发生或传递',
          aliaName: 'B06一般机械振动的发生或传递',
          code: 'B06',
          icon: null,
          cover: null,
          sort: 6,
          description: null,
          parentIds: '2',
          parentId: 2,
          children: [],
        },
        {
          id: 30,
          name: 'B07将固体从固体中分离；分选',
          aliaName: 'B07将固体从固体中分离；分选',
          code: 'B07',
          icon: null,
          cover: null,
          sort: 7,
          description: null,
          parentIds: '2',
          parentId: 2,
          children: [],
        },
        {
          id: 31,
          name: 'B08清洁',
          aliaName: 'B08清洁',
          code: 'B08',
          icon: null,
          cover: null,
          sort: 8,
          description: null,
          parentIds: '2',
          parentId: 2,
          children: [],
        },
        {
          id: 32,
          name: 'B09固体废物的处理；被污染土壤的再生〔3，6〕',
          aliaName: 'B09固体废物的处理；被污染土壤的再生〔3，6〕',
          code: 'B09',
          icon: null,
          cover: null,
          sort: 9,
          description: null,
          parentIds: '2',
          parentId: 2,
          children: [],
        },
        {
          id: 33,
          name: 'B21基本上无切削的金属机械加工；金属冲压',
          aliaName: 'B21基本上无切削的金属机械加工；金属冲压',
          code: 'B21',
          icon: null,
          cover: null,
          sort: 10,
          description: null,
          parentIds: '2',
          parentId: 2,
          children: [],
        },
        {
          id: 34,
          name: 'B22铸造；粉末冶金',
          aliaName: 'B22铸造；粉末冶金',
          code: 'B22',
          icon: null,
          cover: null,
          sort: 11,
          description: null,
          parentIds: '2',
          parentId: 2,
          children: [],
        },
        {
          id: 35,
          name: 'B23机床；其他类目中不包括的金属加工',
          aliaName: 'B23机床；其他类目中不包括的金属加工',
          code: 'B23',
          icon: null,
          cover: null,
          sort: 12,
          description: null,
          parentIds: '2',
          parentId: 2,
          children: [],
        },
        {
          id: 36,
          name: 'B24磨削；抛光',
          aliaName: 'B24磨削；抛光',
          code: 'B24',
          icon: null,
          cover: null,
          sort: 13,
          description: null,
          parentIds: '2',
          parentId: 2,
          children: [],
        },
        {
          id: 37,
          name: 'B25手动工具；轻便机动工具；手动器械的手柄；车间设备；机械手',
          aliaName: 'B25手动工具；轻便机动工具；手动器械的手柄；车间设备；机械手',
          code: 'B25',
          icon: null,
          cover: null,
          sort: 14,
          description: null,
          parentIds: '2',
          parentId: 2,
          children: [],
        },
        {
          id: 38,
          name: 'B26手动切割工具；切割；切断',
          aliaName: 'B26手动切割工具；切割；切断',
          code: 'B26',
          icon: null,
          cover: null,
          sort: 15,
          description: null,
          parentIds: '2',
          parentId: 2,
          children: [],
        },
        {
          id: 39,
          name: 'B27 木材或类似材料的加工或保存；一般钉钉机或钉U形钉机',
          aliaName: 'B27 木材或类似材料的加工或保存；一般钉钉机或钉U形钉机',
          code: 'B27',
          icon: null,
          cover: null,
          sort: 16,
          description: null,
          parentIds: '2',
          parentId: 2,
          children: [],
        },
        {
          id: 40,
          name: 'B28加工水泥、黏土或石料',
          aliaName: 'B28加工水泥、黏土或石料',
          code: 'B28',
          icon: null,
          cover: null,
          sort: 17,
          description: null,
          parentIds: '2',
          parentId: 2,
          children: [],
        },
        {
          id: 41,
          name: 'B29塑料的加工；一般处于塑性状态物质的加工',
          aliaName: 'B29塑料的加工；一般处于塑性状态物质的加工',
          code: 'B29',
          icon: null,
          cover: null,
          sort: 18,
          description: null,
          parentIds: '2',
          parentId: 2,
          children: [],
        },
        {
          id: 42,
          name: 'B30压力机',
          aliaName: 'B30压力机',
          code: 'B30',
          icon: null,
          cover: null,
          sort: 19,
          description: null,
          parentIds: '2',
          parentId: 2,
          children: [],
        },
        {
          id: 43,
          name: 'B31纸品或纸板或类似纸的方式加工的材料制品制作；纸或纸板或类似纸的方式加工的材料的加工',
          aliaName: 'B31纸品或纸板或类似纸的方式加工的材料制品制作；纸或纸板或类似纸的方式加工的材料的加工',
          code: 'B31',
          icon: null,
          cover: null,
          sort: 20,
          description: null,
          parentIds: '2',
          parentId: 2,
          children: [],
        },
        {
          id: 44,
          name: 'B32层状产品',
          aliaName: 'B32层状产品',
          code: 'B32',
          icon: null,
          cover: null,
          sort: 21,
          description: null,
          parentIds: '2',
          parentId: 2,
          children: [],
        },
        {
          id: 45,
          name: 'B33附加制造技术〔2015.01〕',
          aliaName: 'B33附加制造技术〔2015.01〕',
          code: 'B33',
          icon: null,
          cover: null,
          sort: 22,
          description: null,
          parentIds: '2',
          parentId: 2,
          children: [],
        },
        {
          id: 46,
          name: 'B41印刷；排版机；打字机；模印机〔4〕',
          aliaName: 'B41印刷；排版机；打字机；模印机〔4〕',
          code: 'B41',
          icon: null,
          cover: null,
          sort: 23,
          description: null,
          parentIds: '2',
          parentId: 2,
          children: [],
        },
        {
          id: 47,
          name: 'B42装订；图册；文件夹；特种印刷品',
          aliaName: 'B42装订；图册；文件夹；特种印刷品',
          code: 'B42',
          icon: null,
          cover: null,
          sort: 24,
          description: null,
          parentIds: '2',
          parentId: 2,
          children: [],
        },
        {
          id: 48,
          name: 'B43书写或绘图器具；办公用品',
          aliaName: 'B43书写或绘图器具；办公用品',
          code: 'B43',
          icon: null,
          cover: null,
          sort: 25,
          description: null,
          parentIds: '2',
          parentId: 2,
          children: [],
        },
        {
          id: 49,
          name: 'B44装饰艺术',
          aliaName: 'B44装饰艺术',
          code: 'B44',
          icon: null,
          cover: null,
          sort: 26,
          description: null,
          parentIds: '2',
          parentId: 2,
          children: [],
        },
        {
          id: 50,
          name: 'B60一般车辆',
          aliaName: 'B60一般车辆',
          code: 'B60',
          icon: null,
          cover: null,
          sort: 27,
          description: null,
          parentIds: '2',
          parentId: 2,
          children: [],
        },
        {
          id: 51,
          name: 'B61铁路',
          aliaName: 'B61铁路',
          code: 'B61',
          icon: null,
          cover: null,
          sort: 28,
          description: null,
          parentIds: '2',
          parentId: 2,
          children: [],
        },
        {
          id: 52,
          name: 'B62无轨陆用车辆',
          aliaName: 'B62无轨陆用车辆',
          code: 'B62',
          icon: null,
          cover: null,
          sort: 29,
          description: null,
          parentIds: '2',
          parentId: 2,
          children: [],
        },
        {
          id: 53,
          name: 'B63船舶或其他水上船只；与船有关的设备',
          aliaName: 'B63船舶或其他水上船只；与船有关的设备',
          code: 'B63',
          icon: null,
          cover: null,
          sort: 30,
          description: null,
          parentIds: '2',
          parentId: 2,
          children: [],
        },
        {
          id: 54,
          name: 'B64飞行器；航空；宇宙航行',
          aliaName: 'B64飞行器；航空；宇宙航行',
          code: 'B64',
          icon: null,
          cover: null,
          sort: 31,
          description: null,
          parentIds: '2',
          parentId: 2,
          children: [],
        },
        {
          id: 55,
          name: 'B65输送；包装；贮存；搬运薄的或细丝状材料',
          aliaName: 'B65输送；包装；贮存；搬运薄的或细丝状材料',
          code: 'B65',
          icon: null,
          cover: null,
          sort: 32,
          description: null,
          parentIds: '2',
          parentId: 2,
          children: [],
        },
        {
          id: 56,
          name: 'B66卷扬；提升；牵引',
          aliaName: 'B66卷扬；提升；牵引',
          code: 'B66',
          icon: null,
          cover: null,
          sort: 33,
          description: null,
          parentIds: '2',
          parentId: 2,
          children: [],
        },
        {
          id: 57,
          name: 'B67开启或封闭瓶子、罐或类似的容器；液体的贮运',
          aliaName: 'B67开启或封闭瓶子、罐或类似的容器；液体的贮运',
          code: 'B67',
          icon: null,
          cover: null,
          sort: 34,
          description: null,
          parentIds: '2',
          parentId: 2,
          children: [],
        },
        {
          id: 58,
          name: 'B68鞍具；家具罩面',
          aliaName: 'B68鞍具；家具罩面',
          code: 'B68',
          icon: null,
          cover: null,
          sort: 35,
          description: null,
          parentIds: '2',
          parentId: 2,
          children: [],
        },
        {
          id: 59,
          name: 'B81微观结构技术〔7〕',
          aliaName: 'B81微观结构技术〔7〕',
          code: 'B81',
          icon: null,
          cover: null,
          sort: 36,
          description: null,
          parentIds: '2',
          parentId: 2,
          children: [],
        },
        {
          id: 60,
          name: 'B82纳米技术〔7〕',
          aliaName: 'B82纳米技术〔7〕',
          code: 'B82',
          icon: null,
          cover: null,
          sort: 37,
          description: null,
          parentIds: '2',
          parentId: 2,
          children: [],
        },
        {
          id: 61,
          name: 'B99本部其他类目中不包括的技术主题〔8〕',
          aliaName: 'B99本部其他类目中不包括的技术主题〔8〕',
          code: 'B99',
          icon: null,
          cover: null,
          sort: 38,
          description: null,
          parentIds: '2',
          parentId: 2,
          children: [],
        },
      ],
    },
    {
      id: 3,
      name: 'C-化学',
      aliaName: 'C-化学',
      code: 'C',
      icon: null,
      cover: null,
      sort: 3,
      description: null,
      parentIds: null,
      parentId: 0,
      children: [
        {
          id: 62,
          name: 'C01无机化学',
          aliaName: 'C01无机化学',
          code: 'C01',
          icon: null,
          cover: null,
          sort: 1,
          description: null,
          parentIds: '3',
          parentId: 3,
          children: [],
        },
        {
          id: 63,
          name: 'C02水、废水、污水或污泥的处理',
          aliaName: 'C02水、废水、污水或污泥的处理',
          code: 'C02',
          icon: null,
          cover: null,
          sort: 5,
          description: null,
          parentIds: '3',
          parentId: 3,
          children: [],
        },
        {
          id: 64,
          name: 'C03 玻璃；矿棉或渣棉',
          aliaName: 'C03 玻璃；矿棉或渣棉',
          code: 'C03',
          icon: null,
          cover: null,
          sort: 9,
          description: null,
          parentIds: '3',
          parentId: 3,
          children: [],
        },
        {
          id: 65,
          name: 'C04水泥；混凝土；人造石；陶瓷；耐火材料〔4〕',
          aliaName: 'C04水泥；混凝土；人造石；陶瓷；耐火材料〔4〕',
          code: 'C04',
          icon: null,
          cover: null,
          sort: 13,
          description: null,
          parentIds: '3',
          parentId: 3,
          children: [],
        },
        {
          id: 66,
          name: 'C05肥料；肥料制造〔4〕',
          aliaName: 'C05肥料；肥料制造〔4〕',
          code: 'C05',
          icon: null,
          cover: null,
          sort: 17,
          description: null,
          parentIds: '3',
          parentId: 3,
          children: [],
        },
        {
          id: 67,
          name: 'C06炸药；火柴',
          aliaName: 'C06炸药；火柴',
          code: 'C06',
          icon: null,
          cover: null,
          sort: 21,
          description: null,
          parentIds: '3',
          parentId: 3,
          children: [],
        },
        {
          id: 68,
          name: 'C07有机化学〔2〕',
          aliaName: 'C07有机化学〔2〕',
          code: 'C07',
          icon: null,
          cover: null,
          sort: 25,
          description: null,
          parentIds: '3',
          parentId: 3,
          children: [],
        },
        {
          id: 69,
          name: 'C08有机高分子化合物；其制备或化学加工；以其为基料的组合物',
          aliaName: 'C08有机高分子化合物；其制备或化学加工；以其为基料的组合物',
          code: 'C08',
          icon: null,
          cover: null,
          sort: 29,
          description: null,
          parentIds: '3',
          parentId: 3,
          children: [],
        },
        {
          id: 70,
          name: 'C09染料；涂料；抛光剂；天然树脂；黏合剂；其他类目不包含的组合物；其他类目不包含的材料的应用',
          aliaName: 'C09染料；涂料；抛光剂；天然树脂；黏合剂；其他类目不包含的组合物；其他类目不包含的材料的应用',
          code: 'C09',
          icon: null,
          cover: null,
          sort: 33,
          description: null,
          parentIds: '3',
          parentId: 3,
          children: [],
        },
        {
          id: 71,
          name: 'C10石油、煤气及炼焦工业；含一氧化碳的工业气体；燃料；润滑剂；泥煤',
          aliaName: 'C10石油、煤气及炼焦工业；含一氧化碳的工业气体；燃料；润滑剂；泥煤',
          code: 'C10',
          icon: null,
          cover: null,
          sort: 37,
          description: null,
          parentIds: '3',
          parentId: 3,
          children: [],
        },
        {
          id: 72,
          name: 'C11动物或植物油、脂、脂肪物质或蜡；由此制取的脂肪酸；洗涤剂；蜡烛',
          aliaName: 'C11动物或植物油、脂、脂肪物质或蜡；由此制取的脂肪酸；洗涤剂；蜡烛',
          code: 'C11',
          icon: null,
          cover: null,
          sort: 41,
          description: null,
          parentIds: '3',
          parentId: 3,
          children: [],
        },
        {
          id: 73,
          name: 'C12生物化学；啤酒；烈性酒；果汁酒；醋；微生物学；酶学；突变或遗传工程',
          aliaName: 'C12生物化学；啤酒；烈性酒；果汁酒；醋；微生物学；酶学；突变或遗传工程',
          code: 'C12',
          icon: null,
          cover: null,
          sort: 45,
          description: null,
          parentIds: '3',
          parentId: 3,
          children: [],
        },
        {
          id: 74,
          name: 'C13 糖工业〔4〕',
          aliaName: 'C13 糖工业〔4〕',
          code: 'C13',
          icon: null,
          cover: null,
          sort: 49,
          description: null,
          parentIds: '3',
          parentId: 3,
          children: [],
        },
        {
          id: 75,
          name:
            'C14使用化学药剂、酶类或微生物处理小原皮、大原皮或皮革的工艺，如鞣制、浸渍或整饰；其所用的设备；鞣制组合物（皮革或毛皮的漂白入D06L；皮革或毛皮的染色入D06P）',
          aliaName:
            'C14使用化学药剂、酶类或微生物处理小原皮、大原皮或皮革的工艺，如鞣制、浸渍或整饰；其所用的设备；鞣制组合物（皮革或毛皮的漂白入D06L；皮革或毛皮的染色入D06P）',
          code: 'C14',
          icon: null,
          cover: null,
          sort: 53,
          description: null,
          parentIds: '3',
          parentId: 3,
          children: [],
        },
        {
          id: 76,
          name: 'C21铁的冶金',
          aliaName: 'C21铁的冶金',
          code: 'C21',
          icon: null,
          cover: null,
          sort: 57,
          description: null,
          parentIds: '3',
          parentId: 3,
          children: [],
        },
        {
          id: 77,
          name: 'C22冶金；黑色或有色金属合金；合金或有色金属的处理',
          aliaName: 'C22冶金；黑色或有色金属合金；合金或有色金属的处理',
          code: 'C22',
          icon: null,
          cover: null,
          sort: 61,
          description: null,
          parentIds: '3',
          parentId: 3,
          children: [],
        },
        {
          id: 78,
          name:
            'C23对金属材料的镀覆；用金属材料对材料的镀覆；表面化学处理；金属材料的扩散处理；真空蒸发法、溅射法、离子注入法或化学气相沉积法的一般镀覆；金属材料腐蚀或积垢的一般抑制〔2〕',
          aliaName:
            'C23对金属材料的镀覆；用金属材料对材料的镀覆；表面化学处理；金属材料的扩散处理；真空蒸发法、溅射法、离子注入法或化学气相沉积法的一般镀覆；金属材料腐蚀或积垢的一般抑制〔2〕',
          code: 'C23',
          icon: null,
          cover: null,
          sort: 65,
          description: null,
          parentIds: '3',
          parentId: 3,
          children: [],
        },
        {
          id: 79,
          name: 'C25电解或电泳工艺；其所用设备〔4〕',
          aliaName: 'C25电解或电泳工艺；其所用设备〔4〕',
          code: 'C25',
          icon: null,
          cover: null,
          sort: 69,
          description: null,
          parentIds: '3',
          parentId: 3,
          children: [],
        },
        {
          id: 80,
          name: 'C30晶体生长〔3〕',
          aliaName: 'C30晶体生长〔3〕',
          code: 'C30',
          icon: null,
          cover: null,
          sort: 73,
          description: null,
          parentIds: '3',
          parentId: 3,
          children: [],
        },
        {
          id: 81,
          name: 'C40 组合技术〔8〕',
          aliaName: 'C40 组合技术〔8〕',
          code: 'C40',
          icon: null,
          cover: null,
          sort: 77,
          description: null,
          parentIds: '3',
          parentId: 3,
          children: [],
        },
        {
          id: 82,
          name: 'C99本部其他类目不包括的技术主题〔8〕',
          aliaName: 'C99本部其他类目不包括的技术主题〔8〕',
          code: 'C99',
          icon: null,
          cover: null,
          sort: 81,
          description: null,
          parentIds: '3',
          parentId: 3,
          children: [],
        },
      ],
    },
    {
      id: 4,
      name: 'D-纺织；造纸',
      aliaName: 'D-纺织；造纸',
      code: 'D',
      icon: null,
      cover: null,
      sort: 4,
      description: null,
      parentIds: null,
      parentId: 0,
      children: [
        {
          id: 83,
          name: 'D01天然或化学的线或纤维；纺纱或纺丝',
          aliaName: 'D01天然或化学的线或纤维；纺纱或纺丝',
          code: 'D01',
          icon: null,
          cover: null,
          sort: 1,
          description: null,
          parentIds: '4',
          parentId: 4,
          children: [],
        },
        {
          id: 84,
          name: 'D02纱线；纱线或绳索的机械整理；整经或络经',
          aliaName: 'D02纱线；纱线或绳索的机械整理；整经或络经',
          code: 'D02',
          icon: null,
          cover: null,
          sort: 2,
          description: null,
          parentIds: '4',
          parentId: 4,
          children: [],
        },
        {
          id: 85,
          name: 'D03织造',
          aliaName: 'D03织造',
          code: 'D03',
          icon: null,
          cover: null,
          sort: 3,
          description: null,
          parentIds: '4',
          parentId: 4,
          children: [],
        },
        {
          id: 86,
          name: 'D04编织；花边制作；针织；饰带；非织造布',
          aliaName: 'D04编织；花边制作；针织；饰带；非织造布',
          code: 'D04',
          icon: null,
          cover: null,
          sort: 4,
          description: null,
          parentIds: '4',
          parentId: 4,
          children: [],
        },
        {
          id: 87,
          name: 'D05缝纫；绣花；簇绒',
          aliaName: 'D05缝纫；绣花；簇绒',
          code: 'D05',
          icon: null,
          cover: null,
          sort: 5,
          description: null,
          parentIds: '4',
          parentId: 4,
          children: [],
        },
        {
          id: 88,
          name: 'D06织物等的处理；洗涤；其他类不包括的柔性材料',
          aliaName: 'D06织物等的处理；洗涤；其他类不包括的柔性材料',
          code: 'D06',
          icon: null,
          cover: null,
          sort: 6,
          description: null,
          parentIds: '4',
          parentId: 4,
          children: [],
        },
        {
          id: 89,
          name: 'D07绳；除电缆以外的缆索',
          aliaName: 'D07绳；除电缆以外的缆索',
          code: 'D07',
          icon: null,
          cover: null,
          sort: 7,
          description: null,
          parentIds: '4',
          parentId: 4,
          children: [],
        },
        {
          id: 90,
          name: 'D21造纸；纤维素的生产',
          aliaName: 'D21造纸；纤维素的生产',
          code: 'D21',
          icon: null,
          cover: null,
          sort: 8,
          description: null,
          parentIds: '4',
          parentId: 4,
          children: [],
        },
        {
          id: 91,
          name: 'D99本部其他类目不包括的技术主题〔8〕',
          aliaName: 'D99本部其他类目不包括的技术主题〔8〕',
          code: 'D99',
          icon: null,
          cover: null,
          sort: 9,
          description: null,
          parentIds: '4',
          parentId: 4,
          children: [],
        },
      ],
    },
    {
      id: 5,
      name: 'E-固定建筑物',
      aliaName: 'E-固定建筑物',
      code: 'E',
      icon: null,
      cover: null,
      sort: 5,
      description: null,
      parentIds: null,
      parentId: 0,
      children: [
        {
          id: 92,
          name: 'E01道路、铁路或桥梁的建筑',
          aliaName: 'E01道路、铁路或桥梁的建筑',
          code: 'E01',
          icon: null,
          cover: null,
          sort: 1,
          description: null,
          parentIds: '5',
          parentId: 5,
          children: [],
        },
        {
          id: 93,
          name: 'E02水利工程；基础；疏浚',
          aliaName: 'E02水利工程；基础；疏浚',
          code: 'E02',
          icon: null,
          cover: null,
          sort: 2,
          description: null,
          parentIds: '5',
          parentId: 5,
          children: [],
        },
        {
          id: 94,
          name: 'E03给水；排水',
          aliaName: 'E03给水；排水',
          code: 'E03',
          icon: null,
          cover: null,
          sort: 3,
          description: null,
          parentIds: '5',
          parentId: 5,
          children: [],
        },
        {
          id: 95,
          name: 'E04建筑物',
          aliaName: 'E04建筑物',
          code: 'E04',
          icon: null,
          cover: null,
          sort: 4,
          description: null,
          parentIds: '5',
          parentId: 5,
          children: [],
        },
        {
          id: 96,
          name: 'E05锁；钥匙；门窗零件；保险箱',
          aliaName: 'E05锁；钥匙；门窗零件；保险箱',
          code: 'E05',
          icon: null,
          cover: null,
          sort: 5,
          description: null,
          parentIds: '5',
          parentId: 5,
          children: [],
        },
        {
          id: 97,
          name: 'E06一般门、窗、百叶窗或卷辊遮帘；梯子',
          aliaName: 'E06一般门、窗、百叶窗或卷辊遮帘；梯子',
          code: 'E06',
          icon: null,
          cover: null,
          sort: 6,
          description: null,
          parentIds: '5',
          parentId: 5,
          children: [],
        },
        {
          id: 98,
          name: 'E21土层或岩石的钻进；采矿',
          aliaName: 'E21土层或岩石的钻进；采矿',
          code: 'E21',
          icon: null,
          cover: null,
          sort: 7,
          description: null,
          parentIds: '5',
          parentId: 5,
          children: [],
        },
        {
          id: 99,
          name: 'E99本部其他类目不包括的技术主题〔8〕',
          aliaName: 'E99本部其他类目不包括的技术主题〔8〕',
          code: 'E99',
          icon: null,
          cover: null,
          sort: 8,
          description: null,
          parentIds: '5',
          parentId: 5,
          children: [],
        },
      ],
    },
    {
      id: 6,
      name: 'F-机械工程；照明；加热；武器；爆破',
      aliaName: 'F-机械工程；照明；加热；武器；爆破',
      code: 'F',
      icon: null,
      cover: null,
      sort: 6,
      description: null,
      parentIds: null,
      parentId: 0,
      children: [
        {
          id: 100,
          name: 'F01一般机器或发动机；一般的发动机装置；蒸汽机',
          aliaName: 'F01一般机器或发动机；一般的发动机装置；蒸汽机',
          code: 'F01',
          icon: null,
          cover: null,
          sort: 1,
          description: null,
          parentIds: '6',
          parentId: 6,
          children: [],
        },
        {
          id: 101,
          name: 'F02燃烧发动机；热气或燃烧生成物的发动机装置',
          aliaName: 'F02燃烧发动机；热气或燃烧生成物的发动机装置',
          code: 'F02',
          icon: null,
          cover: null,
          sort: 2,
          description: null,
          parentIds: '6',
          parentId: 6,
          children: [],
        },
        {
          id: 102,
          name: 'F03液力机械或液力发动机；风力、弹力或重力发动机；其他类目中不包括的产生机械动力或反推力的发动机',
          aliaName: 'F03液力机械或液力发动机；风力、弹力或重力发动机；其他类目中不包括的产生机械动力或反推力的发动机',
          code: 'F03',
          icon: null,
          cover: null,
          sort: 3,
          description: null,
          parentIds: '6',
          parentId: 6,
          children: [],
        },
        {
          id: 103,
          name: 'F04液体变容式机械；液体泵或弹性流体泵',
          aliaName: 'F04液体变容式机械；液体泵或弹性流体泵',
          code: 'F04',
          icon: null,
          cover: null,
          sort: 4,
          description: null,
          parentIds: '6',
          parentId: 6,
          children: [],
        },
        {
          id: 104,
          name: 'F15流体压力执行机构；一般液压技术和气动技术',
          aliaName: 'F15流体压力执行机构；一般液压技术和气动技术',
          code: 'F15',
          icon: null,
          cover: null,
          sort: 5,
          description: null,
          parentIds: '6',
          parentId: 6,
          children: [],
        },
        {
          id: 105,
          name: 'F16工程元件或部件；为产生和保持机器或设备的有效运行的一般措施；一般绝热',
          aliaName: 'F16工程元件或部件；为产生和保持机器或设备的有效运行的一般措施；一般绝热',
          code: 'F16',
          icon: null,
          cover: null,
          sort: 6,
          description: null,
          parentIds: '6',
          parentId: 6,
          children: [],
        },
        {
          id: 106,
          name: 'F17气体或液体的贮存或分配',
          aliaName: 'F17气体或液体的贮存或分配',
          code: 'F17',
          icon: null,
          cover: null,
          sort: 7,
          description: null,
          parentIds: '6',
          parentId: 6,
          children: [],
        },
        {
          id: 107,
          name: 'F21照明',
          aliaName: 'F21照明',
          code: 'F21',
          icon: null,
          cover: null,
          sort: 8,
          description: null,
          parentIds: '6',
          parentId: 6,
          children: [],
        },
        {
          id: 108,
          name: 'F22蒸汽的发生',
          aliaName: 'F22蒸汽的发生',
          code: 'F22',
          icon: null,
          cover: null,
          sort: 9,
          description: null,
          parentIds: '6',
          parentId: 6,
          children: [],
        },
        {
          id: 109,
          name: 'F23燃烧设备；燃烧方法',
          aliaName: 'F23燃烧设备；燃烧方法',
          code: 'F23',
          icon: null,
          cover: null,
          sort: 10,
          description: null,
          parentIds: '6',
          parentId: 6,
          children: [],
        },
        {
          id: 110,
          name: 'F24供热；炉灶；通风',
          aliaName: 'F24供热；炉灶；通风',
          code: 'F24',
          icon: null,
          cover: null,
          sort: 11,
          description: null,
          parentIds: '6',
          parentId: 6,
          children: [],
        },
        {
          id: 111,
          name: 'F26干燥',
          aliaName: 'F26干燥',
          code: 'F26',
          icon: null,
          cover: null,
          sort: 12,
          description: null,
          parentIds: '6',
          parentId: 6,
          children: [],
        },
        {
          id: 139,
          name: 'F25制冷或冷却；加热和制冷的联合系统；热泵系统；冰的制造或储存；气体的液化或固化',
          aliaName: 'F25制冷或冷却；加热和制冷的联合系统；热泵系统；冰的制造或储存；气体的液化或固化',
          code: 'F25',
          icon: null,
          cover: null,
          sort: 12,
          description: null,
          parentIds: '6',
          parentId: 6,
          children: [],
        },
        {
          id: 112,
          name: 'F27炉；窑；烘烤炉；蒸馏炉〔4〕',
          aliaName: 'F27炉；窑；烘烤炉；蒸馏炉〔4〕',
          code: 'F27',
          icon: null,
          cover: null,
          sort: 13,
          description: null,
          parentIds: '6',
          parentId: 6,
          children: [],
        },
        {
          id: 113,
          name: 'F28一般热交换',
          aliaName: 'F28一般热交换',
          code: 'F28',
          icon: null,
          cover: null,
          sort: 14,
          description: null,
          parentIds: '6',
          parentId: 6,
          children: [],
        },
        {
          id: 114,
          name: 'F41武器',
          aliaName: 'F41武器',
          code: 'F41',
          icon: null,
          cover: null,
          sort: 15,
          description: null,
          parentIds: '6',
          parentId: 6,
          children: [],
        },
        {
          id: 115,
          name: 'F42弹药；爆破',
          aliaName: 'F42弹药；爆破',
          code: 'F42',
          icon: null,
          cover: null,
          sort: 16,
          description: null,
          parentIds: '6',
          parentId: 6,
          children: [],
        },
        {
          id: 116,
          name: 'F99本部其他类目不包括的技术主题〔8〕',
          aliaName: 'F99本部其他类目不包括的技术主题〔8〕',
          code: 'F99',
          icon: null,
          cover: null,
          sort: 17,
          description: null,
          parentIds: '6',
          parentId: 6,
          children: [],
        },
      ],
    },
    {
      id: 7,
      name: 'G-物理',
      aliaName: 'G-物理',
      code: 'G',
      icon: null,
      cover: null,
      sort: 7,
      description: null,
      parentIds: null,
      parentId: 0,
      children: [
        {
          id: 117,
          name: 'G01测量；测试',
          aliaName: 'G01测量；测试',
          code: 'G01',
          icon: null,
          cover: null,
          sort: 1,
          description: null,
          parentIds: '7',
          parentId: 7,
          children: [],
        },
        {
          id: 118,
          name: 'G02光学',
          aliaName: 'G02光学',
          code: 'G02',
          icon: null,
          cover: null,
          sort: 2,
          description: null,
          parentIds: '7',
          parentId: 7,
          children: [],
        },
        {
          id: 119,
          name: 'G03摄影术；电影术；利用了光波以外其他波的类似技术；电记录术；全息摄影术〔4〕',
          aliaName: 'G03摄影术；电影术；利用了光波以外其他波的类似技术；电记录术；全息摄影术〔4〕',
          code: 'G03',
          icon: null,
          cover: null,
          sort: 3,
          description: null,
          parentIds: '7',
          parentId: 7,
          children: [],
        },
        {
          id: 120,
          name: 'G04测时学',
          aliaName: 'G04测时学',
          code: 'G04',
          icon: null,
          cover: null,
          sort: 4,
          description: null,
          parentIds: '7',
          parentId: 7,
          children: [],
        },
        {
          id: 121,
          name: 'G05控制；调节',
          aliaName: 'G05控制；调节',
          code: 'G05',
          icon: null,
          cover: null,
          sort: 5,
          description: null,
          parentIds: '7',
          parentId: 7,
          children: [],
        },
        {
          id: 122,
          name: 'G06计算；推算；计数',
          aliaName: 'G06计算；推算；计数',
          code: 'G06',
          icon: null,
          cover: null,
          sort: 6,
          description: null,
          parentIds: '7',
          parentId: 7,
          children: [],
        },
        {
          id: 123,
          name: 'G07核算装置',
          aliaName: 'G07核算装置',
          code: 'G07',
          icon: null,
          cover: null,
          sort: 7,
          description: null,
          parentIds: '7',
          parentId: 7,
          children: [],
        },
        {
          id: 124,
          name: 'G08信号装置',
          aliaName: 'G08信号装置',
          code: 'G08',
          icon: null,
          cover: null,
          sort: 8,
          description: null,
          parentIds: '7',
          parentId: 7,
          children: [],
        },
        {
          id: 125,
          name: 'G09教育；密码术；显示；广告；印鉴',
          aliaName: 'G09教育；密码术；显示；广告；印鉴',
          code: 'G09',
          icon: null,
          cover: null,
          sort: 9,
          description: null,
          parentIds: '7',
          parentId: 7,
          children: [],
        },
        {
          id: 126,
          name: 'G10乐器；声学',
          aliaName: 'G10乐器；声学',
          code: 'G10',
          icon: null,
          cover: null,
          sort: 10,
          description: null,
          parentIds: '7',
          parentId: 7,
          children: [],
        },
        {
          id: 127,
          name: 'G11 信息存储',
          aliaName: 'G11 信息存储',
          code: 'G11',
          icon: null,
          cover: null,
          sort: 11,
          description: null,
          parentIds: '7',
          parentId: 7,
          children: [],
        },
        {
          id: 128,
          name: 'G12仪器的零部件',
          aliaName: 'G12仪器的零部件',
          code: 'G12',
          icon: null,
          cover: null,
          sort: 12,
          description: null,
          parentIds: '7',
          parentId: 7,
          children: [],
        },
        {
          id: 129,
          name: 'G16特别适用于特定应用领域的信息通信技术〔ICT〕〔2018.01〕',
          aliaName: 'G16特别适用于特定应用领域的信息通信技术〔ICT〕〔2018.01〕',
          code: 'G16',
          icon: null,
          cover: null,
          sort: 13,
          description: null,
          parentIds: '7',
          parentId: 7,
          children: [],
        },
        {
          id: 130,
          name: 'G21核物理；核工程',
          aliaName: 'G21核物理；核工程',
          code: 'G21',
          icon: null,
          cover: null,
          sort: 14,
          description: null,
          parentIds: '7',
          parentId: 7,
          children: [],
        },
        {
          id: 131,
          name: 'G99不包含在本部其他类目中的技术主题〔8〕',
          aliaName: 'G99不包含在本部其他类目中的技术主题〔8〕',
          code: 'G99',
          icon: null,
          cover: null,
          sort: 15,
          description: null,
          parentIds: '7',
          parentId: 7,
          children: [],
        },
      ],
    },
    {
      id: 8,
      name: 'H-电学',
      aliaName: 'H-电学',
      code: 'H',
      icon: null,
      cover: null,
      sort: 8,
      description: null,
      parentIds: null,
      parentId: 0,
      children: [
        {
          id: 132,
          name: 'H01基本电气元件',
          aliaName: 'H01基本电气元件',
          code: 'H01',
          icon: null,
          cover: null,
          sort: 2,
          description: null,
          parentIds: '8',
          parentId: 8,
          children: [],
        },
        {
          id: 133,
          name: 'H02发电、变电或配电',
          aliaName: 'H02发电、变电或配电',
          code: 'H02',
          icon: null,
          cover: null,
          sort: 3,
          description: null,
          parentIds: '8',
          parentId: 8,
          children: [],
        },
        {
          id: 134,
          name: 'H03 基本电子电路',
          aliaName: 'H03 基本电子电路',
          code: 'H03',
          icon: null,
          cover: null,
          sort: 4,
          description: null,
          parentIds: '8',
          parentId: 8,
          children: [],
        },
        {
          id: 135,
          name: 'H04电通信技术',
          aliaName: 'H04电通信技术',
          code: 'H04',
          icon: null,
          cover: null,
          sort: 5,
          description: null,
          parentIds: '8',
          parentId: 8,
          children: [],
        },
        {
          id: 136,
          name: 'H05其他类目不包含的电技术',
          aliaName: 'H05其他类目不包含的电技术',
          code: 'H05',
          icon: null,
          cover: null,
          sort: 6,
          description: null,
          parentIds: '8',
          parentId: 8,
          children: [],
        },
        {
          id: 137,
          name: 'H99本部中其他类目不包括的技术主题〔8〕',
          aliaName: 'H99本部中其他类目不包括的技术主题〔8〕',
          code: 'H99',
          icon: null,
          cover: null,
          sort: 7,
          description: null,
          parentIds: '8',
          parentId: 8,
          children: [],
        },
      ],
    },
  ],
};

export default data.data;
